version: 2
project_name: "DeveloperTerminal"

before:
  hooks: []

builds:
  - id: unix
    main: ./cmd/devterminal
    binary: "DeveloperTerminal"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

  - id: windows
    main: ./cmd/devterminal
    binary: "DeveloperTerminal"
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: nix
    ids:
      - unix
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ title .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}
    wrap_in_directory: true
    files:
      - README.md
      - LICENSE
    allow_different_binary_count: true

  - id: windows
    ids:
      - windows
    formats:
      - zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_Windows_{{ if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}
    wrap_in_directory: true
    files:
      - README.md
      - LICENSE
    allow_different_binary_count: true

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^build:"
      - "^remove"
      - "^first commit"
      - "^second commit"

release:
  replace_existing_artifacts: true